name: tugas_akhir2
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  table_calendar: ^3.0.9
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  assets:
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/absen.png
    - assets/images/absen2.png
    - assets/images/cuti.png
    - assets/images/pzn.png
    - assets/images/bunga.jpg
    - assets/images/bg1.jpeg
    - assets/images/defaultpp.jpeg

  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
